# Title shown in Application Information tab.
title: "OKE Quick Onboarding"
# Sub Title shown in Application Information tab.
description: "This is Quick OKE Onboarding stack"
# informationalText: "This is quick OKE Onboarding stack"
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.

logoUrl: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHN0eWxlPSJiYWNrZ3JvdW5kOiB0cmFuc3BhcmVudDsgYmFja2dyb3VuZC1jb2xvcjogdHJhbnNwYXJlbnQ7IiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iODFweCIgaGVpZ2h0PSI4MHB4IiB2aWV3Qm94PSItMC41IC0wLjUgODEgODAiPjxkZWZzLz48Zz48ZyBkYXRhLWNlbGwtaWQ9IjAiPjxnIGRhdGEtY2VsbC1pZD0iMSI+PGcgZGF0YS1jZWxsLWlkPSJ3SWRiQ2ZLZWZzNmNMSHIybjhyRC0xNCI+PGc+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjgxIiBoZWlnaHQ9IjgwIiBmaWxsPSJub25lIiBzdHJva2U9Im5vbmUiIHBvaW50ZXItZXZlbnRzPSJhbGwiLz48L2c+PGcgZGF0YS1jZWxsLWlkPSJ3SWRiQ2ZLZWZzNmNMSHIybjhyRC0xNSI+PGc+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjgxIiBoZWlnaHQ9IjgwIiBmaWxsPSJub25lIiBzdHJva2U9Im5vbmUiIHBvaW50ZXItZXZlbnRzPSJhbGwiLz48L2c+PGcgZGF0YS1jZWxsLWlkPSJ3SWRiQ2ZLZWZzNmNMSHIybjhyRC0xNiI+PGc+PHBhdGggZD0iTSA1LjE5IDc4Ljg2IEMgMi44OSA3OC44NiAwLjk2IDc2Ljk1IDAuOTYgNzQuNjcgTCAwLjk2IDUuMTMgQyAwLjk2IDIuODUgMi44OSAwLjk1IDUuMTkgMC45NSBMIDc1LjgxIDAuOTUgQyA3OC4xMSAwLjk1IDgwLjA0IDIuODUgODAuMDQgNS4xMyBMIDgwLjA0IDc0Ljg3IEMgODAuMDQgNzcuMTUgNzguMTEgNzkuMDUgNzUuODEgNzkuMDUgTCA1LjE5IDc4Ljg2IEwgNS4xOSA3OC44NiIgZmlsbD0iI2ZmZmZmZiIgc3Ryb2tlPSJub25lIiBwb2ludGVyLWV2ZW50cz0iYWxsIiBzdHlsZT0iZmlsbDogcmdiKDI1NSwgMjU1LCAyNTUpOyIvPjwvZz48L2c+PGcgZGF0YS1jZWxsLWlkPSJ3SWRiQ2ZLZWZzNmNMSHIybjhyRC0xNyI+PGc+PHBhdGggZD0iTSA3NS42MSAxLjkgQyA3Ny4zNSAxLjkgNzguODkgMy40MyA3OC44OSA1LjE0IEwgNzguODkgNzUuMDUgQyA3OC44OSA3Ni43NiA3Ny4zNSA3OC4yOSA3NS42MSA3OC4yOSBMIDUuMTkgNzguMjkgQyAzLjQ3IDc4LjEgMS45MyA3Ni41NyAxLjkzIDc0Ljg2IEwgMS45MyA1LjE0IEMgMS45MyAzLjQzIDMuNDcgMS45IDUuMTkgMS45IEwgNzUuNjEgMS45IEwgNzUuNjEgMS45IE0gNzUuNjEgMCBMIDUuMTkgMCBDIDIuMzEgMCAwIDIuMjkgMCA1LjE0IEwgMCA3NS4wNSBDIDAgNzcuNzEgMi4zMSA4MCA1LjE5IDgwIEwgNzUuODEgODAgQyA3OC42OSA4MCA4MSA3Ny43MSA4MSA3NC44NiBMIDgxIDUuMTQgQyA4MC44MSAyLjI5IDc4LjUgMCA3NS42MSAwIEwgNzUuNjEgMCIgZmlsbD0iI2ZmZmZmZiIgc3Ryb2tlPSJub25lIiBwb2ludGVyLWV2ZW50cz0iYWxsIiBzdHlsZT0iZmlsbDogcmdiKDI1NSwgMjU1LCAyNTUpOyIvPjwvZz48L2c+PC9nPjxnIGRhdGEtY2VsbC1pZD0id0lkYkNmS2VmczZjTEhyMm44ckQtMTgiPjxnPjxyZWN0IHg9IjEuOTMiIHk9IjEuOSIgd2lkdGg9Ijc3LjE0IiBoZWlnaHQ9Ijc2LjE5IiBmaWxsPSJub25lIiBzdHJva2U9Im5vbmUiIHBvaW50ZXItZXZlbnRzPSJhbGwiLz48L2c+PGcgZGF0YS1jZWxsLWlkPSJ3SWRiQ2ZLZWZzNmNMSHIybjhyRC0xOSI+PGc+PHBhdGggZD0iTSA3NS42MSAxLjkgTCA1LjIgMS45IEMgMy40NyAxLjkgMS45MyAzLjQzIDEuOTMgNS4xNCBMIDEuOTMgNzUuMDUgQyAxLjkzIDc2LjU3IDMuNDcgNzguMSA1LjIgNzguMSBMIDc1LjggNzguMSBDIDc3LjUzIDc4LjEgNzkuMDcgNzYuNTcgNzkuMDcgNzQuODYgTCA3OS4wNyA1LjE0IEMgNzguODggMy40MyA3Ny4zNCAxLjkgNzUuNjEgMS45IEwgNzUuNjEgMS45IE0gNzUuOTkgNzQuODYgQyA3NS45OSA3NS4wNSA3NS44IDc1LjI0IDc1LjYxIDc1LjI0IEwgNS4yIDc1LjI0IEMgNS4wMSA3NS4yNCA0LjgxIDc1LjA1IDQuODEgNzQuODYgTCA0LjgxIDUuMTQgQyA0LjgxIDQuOTUgNS4wMSA0Ljc2IDUuMiA0Ljc2IEwgNzUuOCA0Ljc2IEMgNzUuOTkgNC43NiA3Ni4xOSA0Ljk1IDc2LjE5IDUuMTQgTCA3NS45OSA3NC44NiBMIDc1Ljk5IDc0Ljg2IiBmaWxsPSIjMmQ1OTY3IiBzdHJva2U9Im5vbmUiIHBvaW50ZXItZXZlbnRzPSJhbGwiIHN0eWxlPSJmaWxsOiByZ2IoNDUsIDg5LCAxMDMpOyIvPjwvZz48L2c+PGcgZGF0YS1jZWxsLWlkPSJ3SWRiQ2ZLZWZzNmNMSHIybjhyRC0yMCI+PGc+PHBhdGggZD0iTSAzOC41NyA5LjUyIEwgMjIuMTggOS41MiBMIDIyLjE4IDI1LjcxIEwgMzguNTcgMjUuNzEgTCAzOC41NyA5LjUyIEwgMzguNTcgOS41MiBNIDM1LjgxIDIzLjE3IEwgMjQuOTQgMjMuMTcgTCAyNC45NCAxMi4yNSBMIDM1LjgxIDEyLjI1IEwgMzUuODEgMjMuMTcgTCAzNS44MSAyMy4xNyIgZmlsbD0iIzJkNTk2NyIgc3Ryb2tlPSJub25lIiBwb2ludGVyLWV2ZW50cz0iYWxsIiBzdHlsZT0iZmlsbDogcmdiKDQ1LCA4OSwgMTAzKTsiLz48L2c+PC9nPjxnIGRhdGEtY2VsbC1pZD0id0lkYkNmS2VmczZjTEhyMm44ckQtMjEiPjxnPjxwYXRoIGQ9Ik0gNTcuODYgOS41MiBMIDQxLjQ2IDkuNTIgTCA0MS40NiAyNS43MSBMIDU3Ljg2IDI1LjcxIEMgNTcuNjcgMjUuNzEgNTcuNjcgOS41MiA1Ny44NiA5LjUyIEwgNTcuODYgOS41MiBNIDU1LjA5IDIzLjE3IEwgNDQuMjMgMjMuMTcgTCA0NC4yMyAxMi4yNSBMIDU1LjA5IDEyLjI1IEwgNTUuMDkgMjMuMTcgTCA1NS4wOSAyMy4xNyIgZmlsbD0iIzJkNTk2NyIgc3Ryb2tlPSJub25lIiBwb2ludGVyLWV2ZW50cz0iYWxsIiBzdHlsZT0iZmlsbDogcmdiKDQ1LCA4OSwgMTAzKTsiLz48L2c+PC9nPjxnIGRhdGEtY2VsbC1pZD0id0lkYkNmS2VmczZjTEhyMm44ckQtMjIiPjxnPjxwYXRoIGQ9Ik0gMzQuNDMgMzIuMjQgTCA0NS42MSAzMi4yNCBMIDQ1LjYxIDM2LjYgTCA0OC4yMSAzNy4xNCBMIDQ4LjIxIDI5LjUyIEwgMzEuODIgMjkuNTIgTCAzMS44MiAzNy4xNCBMIDM0LjQzIDM2LjYgTCAzNC40MyAzMi4yNCBMIDM0LjQzIDMyLjI0IiBmaWxsPSIjMmQ1OTY3IiBzdHJva2U9Im5vbmUiIHBvaW50ZXItZXZlbnRzPSJhbGwiIHN0eWxlPSJmaWxsOiByZ2IoNDUsIDg5LCAxMDMpOyIvPjwvZz48L2c+PGcgZGF0YS1jZWxsLWlkPSJ3SWRiQ2ZLZWZzNmNMSHIybjhyRC0yMyI+PGc+PHBhdGggZD0iTSA1My43MiAzMi4zIEwgNjQuODkgMzIuMyBMIDY0Ljg5IDQxLjM1IEwgNjcuNSA0MS45IEwgNjcuNSAyOS41MiBMIDUxLjExIDI5LjUyIEwgNTEuMTEgMzcuODQgTCA1My43MiAzOC41OCBMIDUzLjcyIDMyLjMgTCA1My43MiAzMi4zIiBmaWxsPSIjMmQ1OTY3IiBzdHJva2U9Im5vbmUiIHBvaW50ZXItZXZlbnRzPSJhbGwiIHN0eWxlPSJmaWxsOiByZ2IoNDUsIDg5LCAxMDMpOyIvPjwvZz48L2c+PGcgZGF0YS1jZWxsLWlkPSJ3SWRiQ2ZLZWZzNmNMSHIybjhyRC0yNCI+PGc+PHBhdGggZD0iTSAxNS4xNCAzMi4zIEwgMjYuMzIgMzIuMyBMIDI2LjMyIDM4LjU4IEwgMjguOTMgMzcuODQgTCAyOC45MyAyOS41MiBMIDEyLjU0IDI5LjUyIEwgMTIuNTQgNDEuOSBMIDE1LjE0IDQxLjM1IEwgMTUuMTQgMzIuMyBMIDE1LjE0IDMyLjMiIGZpbGw9IiMyZDU5NjciIHN0cm9rZT0ibm9uZSIgcG9pbnRlci1ldmVudHM9ImFsbCIgc3R5bGU9ImZpbGw6IHJnYig0NSwgODksIDEwMyk7Ii8+PC9nPjwvZz48ZyBkYXRhLWNlbGwtaWQ9IndJZGJDZktlZnM2Y0xIcjJuOHJELTI1Ij48Zz48cGF0aCBkPSJNIDQwLjAyIDM3LjE0IEwgOS42NCA0NC40NCBMIDEwLjAzIDQ1Ljc1IEMgMTMuNDkgNTkuMjIgMjUuNzkgNjguNTcgNDAuMDIgNjguNTcgQyA1NC4yNSA2OC41NyA2Ni43NCA1OS4yMiA3MC4wMSA0NS43NSBMIDcwLjM5IDQ0LjQ0IEwgNDAuMDIgMzcuMTQgTCA0MC4wMiAzNy4xNCBNIDM4LjY4IDQwLjMyIEwgMzguNjggNjUuNzYgQyAyNi43NSA2NS4zOSAxNi41NiA1Ny41MyAxMy4xMSA0Ni41IEwgMzguNjggNDAuMzIgTCAzOC42OCA0MC4zMiBNIDQxLjM2IDY1Ljc2IEwgNDEuMzYgNDAuMzIgTCA2Ni45MyA0Ni41IEMgNjMuNDcgNTcuNTMgNTMuMjkgNjUuMzkgNDEuMzYgNjUuNzYgTCA0MS4zNiA2NS43NiIgZmlsbD0iIzJkNTk2NyIgc3Ryb2tlPSJub25lIiBwb2ludGVyLWV2ZW50cz0iYWxsIiBzdHlsZT0iZmlsbDogcmdiKDQ1LCA4OSwgMTAzKTsiLz48L2c+PC9nPjwvZz48L2c+PC9nPjwvZz48L2c+PC9zdmc+

# source:
#   type: marketplace
#   reference: 16132843

source:
  type: web


locale: "en"
variableGroups:
  - title: "Basic Hidden"
    variables:
    - tenancy_ocid
    - region
    - user_ocid
    visible: false

  - title: "OKE Network Configuration"
    variables:
    - create_vcn
    - oke_vcn_compartment_id
    - vcn_cidrs
    - vcn_id

  - title: "OKE Cluster Configuration"
    variables:
    - oke_cluster_name
    - oke_cluster_compartment_id
    - oke_kubernetes_version
    - oke_show_advanced_options
    - oke_network_type
    - oke_cluster_endpoint_visibility

  - title: "OKE Node Pool Configuration"
    variables:
    - oke_create_multiple_node_pool
    - oke_node_pool_name   
    - oke_node_pool_size
    - oke_node_pool_instance_shape
    - oke_node_boot_volume_size
    - oke_enable_node_pool   
    - oke_node_pool_properties
    - oke_ssh_private_key
    - oke_ssh_public_key

variables:
  oke_cluster_compartment_id:
    type: oci:identity:compartment:id
    title: "OKE Cluster Compartment"
    description: "The compartment where you want to create OKE cluster"
    default: compartment_ocid
    required: true

  oke_cluster_name:
    type: string
    title: "OKE Cluster Name"
    description: "Provide OKE cluster name"
    default: "okecluster"
    required: false
    pattern: "^[A-Za-z0-9_-]{3,20}$"

  oke_kubernetes_version:
    type: oci:kubernetes:versions:id
    title: "Kubernetes Version"
    description: "Provide Kubernetes Version"
    dependsOn:
      compartmentId: oke_cluster_compartment_id
      clusterOptionId: "all"
    required: true
    visible: true

  oke_show_advanced_options:
    type: boolean
    default: false
    title: "Advanced options"
    description: "Shows advanced options for OKE"
    visible: true

  oke_network_type:
    type: enum
    enum:
    - "Flannel"
    - "VCN-native pod networking"
    title: "OKE Network Type"
    description: "Provide Network Type"
    required: true
    visible:
      and:
        - oke_show_advanced_options

  oke_cluster_endpoint_visibility:
    type: enum
    enum:
    - "Private"
    - "Public"
    default: "Private"
    title: "Choose Kubernetes API Endpoint visibility type"
    description: "Kubernetes API Endpoint visibility type"
    required: true
    visible:
      and:
        - oke_show_advanced_options

  create_vcn:
    type: boolean
    title: "Create new VCN"
    description: "Whether to create a Virtual Cloud Network for OKE Cluster"
    required: false
    visible: true

  oke_vcn_compartment_id:
    type: oci:identity:compartment:id
    title: "OKE VCN Compartment"
    description: "The compartment where you want to create OKE VCN"
    default: compartment_ocid
    required: true

  vcn_cidrs:
    type: array
    items:
      type: string
    title: "List of VCN cidrs"
    description: "The list of IPv4 CIDR blocks the VCN will use"
    default: ["10.0.0.0/16"]
    required: true
    visible:
      and:
        - create_vcn

  vcn_id:
    type: oci:core:vcn:id
    title: Existing VCN
    description: An existing Virtual Cloud Network (VCN) where OKE Cluster will be provisioned"
    dependsOn:
      compartmentId: oke_vcn_compartment_id 
    required: true
    visible:
      not:
        - create_vcn

  oke_create_multiple_node_pool:
    type: boolean
    default: false
    title: "Create Multiple Node Pools"
    description: "Whether to create more than one node pool for OKE cluster"
    visible: true

  # oke_node_pool_name:
  #   type: string
  #   title: "Node Pool Name"
  #   description: "OKE Cluster Node Pool Name"
  #   default: "nodepool-1"
  #   required: false
  #   pattern: "^[A-Za-z0-9-]+$"
  #   visible:
  #     and:
  #       - eq:
  #         - oke_node_pool_size
  #         - 1

  oke_node_pool_name:
    type: string
    title: "Node Pool Name"
    description: "OKE Cluster Node Pool Name"
    default: "nodepool-1"
    required: false
    pattern: "^[A-Za-z0-9-]+$"
    visible:
      not:
        - oke_create_multiple_node_pool

  oke_node_pool_size:
    type: number
    title: "OKE Cluster Node Pool Size"
    description: "The number of nodes in the OKE cluster node pool"
    default: 1
    required: true
    pattern: "^[0-9]+$"
    visible:
      not:
        - oke_create_multiple_node_pool 

  oke_node_pool_instance_shape:
    type: oci:core:instanceshapewithflex:name
    title: "Select a shape for the Worker Nodes instances"
    required: true
    dependsOn:
      compartmentId: oke_cluster_compartment_id
    visible:
      not:
        - oke_create_multiple_node_pool 

  oke_node_boot_volume_size:
    type: number
    title: "Node pool boot volume size"
    default: 50
    required: true
    minimum: 50
    visible:
      not:
        - oke_create_multiple_node_pool 

  oke_enable_node_pool:
    type: boolean
    default: true
    title: "Create Node Pool"
    description: "Whether to enable node pool for OKE cluster"
    visible:
      not:
        - oke_create_multiple_node_pool

  oke_node_pool_properties:
    type: object
    title: "OKE Node Pool Properties"
    description: "Multiple Node pool properties"
    default: |
      {
        "node-pools": {
          "nodepool-1": {
            "create": true,
            "mode": "node-pool",
            "size": 1,
            "shape": "VM.Standard.E4.Flex",
            "ocpus": 1,
            "memory": 16,
            "boot_volume_size": 50
          },
          "nodepool-2": {
            "create": true,
            "mode": "node-pool",
            "size": 1,
            "shape": "VM.Standard.E4.Flex",
            "ocpus": 1,
            "memory": 16,
            "boot_volume_size": 50
          }
        }
      }
    visible:
      and:
        - oke_create_multiple_node_pool

  oke_ssh_public_key:
    title: SSH public key
    description: Public SSH key for compute access.
    # renders variable as an SSH key control
    type: oci:core:ssh:publickey
    additionalProps:
      allowMultiple: true
    required: true
    default: []
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"

  oke_ssh_private_key:
    type: file
    title: SSH private key
    description: UPload ssh private key
    required: true

  # oke_cluster_properties:
  #   type: object
  #   title: "OKE Cluster Properties"
  #   description: "OKE Cluster Properties"
  #   default: |
  #     {
  #       "cluster_name": "blue",
  #       "cni": "flannel",
  #       "cluster_type": "enhanced",
  #       "vcn_cidr": ["10.0.0.0/16"],
  #       "bastion_allowed_cidrs": ["0.0.0.0/0"],
  #       "control_plane_is_public": false,
  #       "worker_pools": {
  #         "housekeeping": {
  #           "create": true,
  #           "mode": "node-pool",
  #           "size": 1,
  #           "shape": "VM.Standard.E4.Flex",
  #           "ocpus": 1,
  #           "memory": 16,
  #           "boot_volume_size": 50
  #         }
  #       }
  #     }


outputGroups:
  - title: OKE Details
    outputs:
      - oke_cluster_name

outputs:
  oke_cluster_name:
    type: string
    title: OKE cluster Name
    displayText: OKE Cluster Name
    visible: true
