# Title shown in Application Information tab.
title: "OKE Quick Onboarding"
# Sub Title shown in Application Information tab.
description: "This is Quick OKE Onboarding stack"
informationalText: "This is quick OKE Onboarding stack"
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
# logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708
# logoUrl: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTI4IDEyOCI+CiAgPGRlZnM+CiAgICA8ZmlsdGVyIGlkPSJQYXRoXzI3IiB4PSIwIiB5PSIwIiB3aWR0aD0iNjguMjciIGhlaWdodD0iNjIuOTUxIiBmaWx0ZXJVbml0cz0idXNlclNwYWNlT25Vc2UiPgogICAgICA8ZmVPZmZzZXQgZHg9IjEiIGR5PSIzIiBpbnB1dD0iU291cmNlQWxwaGEiLz4KICAgICAgPGZlR2F1c3NpYW5CbHVyIHN0ZERldmlhdGlvbj0iMyIgcmVzdWx0PSJibHVyIi8+CiAgICAgIDxmZUZsb29kIGZsb29kLW9wYWNpdHk9IjAuNTAyIi8+CiAgICAgIDxmZUNvbXBvc2l0ZSBvcGVyYXRvcj0iaW4iIGluMj0iYmx1ciIvPgogICAgICA8ZmVDb21wb3NpdGUgaW49IlNvdXJjZUdyYXBoaWMiLz4KICAgIDwvZmlsdGVyPgogICAgPGZpbHRlciBpZD0icGF0aDUiIHg9IjE3LjYzNyIgeT0iMTEuNCIgd2lkdGg9IjMyLjUzNyIgaGVpZ2h0PSIzOS4xNzMiIGZpbHRlclVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CiAgICAgIDxmZU9mZnNldCBkeT0iMyIgaW5wdXQ9IlNvdXJjZUFscGhhIi8+CiAgICAgIDxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249IjMiIHJlc3VsdD0iYmx1ci0yIi8+CiAgICAgIDxmZUZsb29kIGZsb29kLW9wYWNpdHk9IjAuMjc1Ii8+CiAgICAgIDxmZUNvbXBvc2l0ZSBvcGVyYXRvcj0iaW4iIGluMj0iYmx1ci0yIi8+CiAgICAgIDxmZUNvbXBvc2l0ZSBpbj0iU291cmNlR3JhcGhpYyIvPgogICAgPC9maWx0ZXI+CiAgPC9kZWZzPgogIDxnIGlkPSJHcm91cF81MCIgZGF0YS1uYW1lPSJHcm91cCA1MCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTIzIC0xNzUpIj4KICAgIDxnIGlkPSJHcm91cF80NCIgZGF0YS1uYW1lPSJHcm91cCA0NCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE3IC0yMjcpIj4KICAgICAgPGcgaWQ9ImFpbHVyb3BoaWxlIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSg1Ni4xNDYgNDI0KSI+CiAgICAgICAgPHBhdGggaWQ9IlBhdGhfMjIiIGRhdGEtbmFtZT0iUGF0aCAyMiIgZD0iTTkyLjQxOSwzOS45M2MxLjM2Ni0zLjc1MywyLjQ1Mi05LjI4OC0uMTM0LTE0LjM0MkExNC4xNTcsMTQuMTU3LDAsMCwxLDkwLjgsMTkuMDc3Yy4wMzYtNi4wNzEuMTI4LTEyLjM5NS4yLTE2LjYzMUEyLjQsMi40LDAsMCwwLDg2Ljg4LjcyNmwtOS41MTUsOS43MjZhMjQuNDcxLDI0LjQ3MSwwLDAsMC0xNC4yOTMsMS4wMzVjLTIuNjg1LTIuNjA2LTcuNzE1LTcuMDI5LTEwLjYtOS41NGEyLjM3LDIuMzcsMCwwLDAtMi42MjMtLjM1MiwyLjQsMi40LDAsMCwwLTEuMzU4LDIuMjc1bC42ODEsMTUuMTUyYTQyLjQ2LDQyLjQ2LDAsMCwxLS43NjksMTAuMjQzQTU4LjY2NCw1OC42NjQsMCwwLDAsNDcuMiw0My40NTksMjYuNzE2LDI2LjcxNiwwLDAsMCwzMi44NzksNDkuNWMtNy44MDYsNi4zMjItMTIuODU3LDE2LjYyMS0xNS4wMTIsMzAuNjEzYTEuMTUsMS4xNSwwLDAsMCwyLjI3NC4zNUMyMi4yMDcsNjcuMDU3LDI2Ljk4LDU3LjI0MSwzNC4zMjcsNTEuMjljNi41NjgtNS4zMTksMTIuOS01LjU4OSwxNC4xLTUuNTg5YTEuMTUsMS4xNSwwLDAsMCwxLjE0Ni0xLjI0OCw1NC41NTksNTQuNTU5LDAsMCwxLDEuMDg4LTE0LjczNyw0NC43NDgsNDQuNzQ4LDAsMCwwLC44MTItMTAuOEw1MC43OTIsMy43NjZhLjA5MS4wOTEsMCwwLDEsLjA1OS0uMS4wODcuMDg3LDAsMCwxLC4xMTIuMDE1YzMuMDY3LDIuNjcxLDguNTc2LDcuNTE3LDExLjAyLDkuOTYyYTEuMTUsMS4xNSwwLDAsMCwxLjI0OC4yNTIsMjIuMDU5LDIyLjA1OSwwLDAsMSwxNC4xMDctMS4wNiwxLjE1MSwxLjE1MSwwLDAsMCwxLjE5Mi0uMjg1TDg4LjUyNCwyLjMzNWEuMDg5LjA4OSwwLDAsMSwuMTE2LS4wMjQuMDg2LjA4NiwwLDAsMSwuMDYzLjFjLS4wNzIsNC4yNDItLjE2NCwxMC41NzUtLjIsMTYuNjU2YTE2LjQ2OCwxNi40NjgsMCwwLDAsMS43MzMsNy41NzNjMi4yMDgsNC4zMTYsMS4yMyw5LjE4My4wMiwxMi41MDdhMTYuNzUyLDE2Ljc1MiwwLDAsMC0uNTA2LDkuNzVjMS42NTQsNi43NDQsMy4zNTgsMTkuOS0zLjgxNywzMi4yMjRhMS4xNSwxLjE1LDAsMSwwLDEuOTg4LDEuMTU3YzcuNTgxLTEzLjAyNCw1LjgtMjYuODQ4LDQuMDYzLTMzLjkzQTE0LjQ2MSwxNC40NjEsMCwwLDEsOTIuNDE5LDM5LjkzWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCAwKSIvPgogICAgICAgIDxwYXRoIGlkPSJQYXRoXzIzIiBkYXRhLW5hbWU9IlBhdGggMjMiIGQ9Ik0yNDQuMDA4LDEyOS42ODVhMS4xNSwxLjE1LDAsMCwwLDIuMywwLDQuNyw0LjcsMCwwLDAtOS4zOTQsMCwxLjE1LDEuMTUsMCwwLDAsMi4zLDAsMi40LDIuNCwwLDAsMSw0Ljc5MywwWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE3Ny4wNjIgLTEwMS4wMjUpIi8+CiAgICAgICAgPHBhdGggaWQ9IlBhdGhfMjQiIGRhdGEtbmFtZT0iUGF0aCAyNCIgZD0iTTMyNS42MTQsMTI0Ljk4OGE0LjcsNC43LDAsMCwwLTQuNyw0LjcsMS4xNSwxLjE1LDAsMSwwLDIuMywwLDIuNCwyLjQsMCwwLDEsNC43OTMsMCwxLjE1LDEuMTUsMCwxLDAsMi4zLDBBNC43LDQuNywwLDAsMCwzMjUuNjE0LDEyNC45ODhaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMjQ0Ljk2IC0xMDEuMDI1KSIvPgogICAgICAgIDxwYXRoIGlkPSJQYXRoXzI1IiBkYXRhLW5hbWU9IlBhdGggMjUiIGQ9Ik0yNzQuOTU3LDE4Mi41MTdhMS4xNSwxLjE1LDAsMCwwLTEuMTUsMS4xNSwzLjMsMy4zLDAsMSwxLTYuNjA2LDAsMS4xNSwxLjE1LDAsMCwwLTIuMywwLDMuMywzLjMsMCwxLDEtNi42MDYsMCwxLjE1LDEuMTUsMCwwLDAtMi4zLDAsNS42LDUuNiwwLDAsMCwxMC4wNTcsMy40LDUuNiw1LjYsMCwwLDAsMTAuMDU3LTMuNEExLjE1LDEuMTUsMCwwLDAsMjc0Ljk1NywxODIuNTE3WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE5Mi40ODMgLTE0Ny41MjUpIi8+CiAgICAgIDwvZz4KICAgIDwvZz4KICAgIDxnIGlkPSJjb252ZXJzYXRpb24tc3BlZWNoLWJ1YmJsZXMtIiB0cmFuc2Zvcm09Im1hdHJpeCgwLjk5NSwgLTAuMTA1LCAwLjEwNSwgMC45OTUsIDMyLjI2NSwgMTk4LjYwMSkiPgogICAgICA8ZyB0cmFuc2Zvcm09Im1hdHJpeCgwLjk5LCAwLjEsIC0wLjEsIDAuOTksIC02LjgyLCAtMTAuNjgpIiBmaWx0ZXI9InVybCgjUGF0aF8yNykiPgogICAgICAgIDxwYXRoIGlkPSJQYXRoXzI3LTIiIGRhdGEtbmFtZT0iUGF0aCAyNyIgZD0iTTIzLjE1NC45MzVjMTIuNzg4LDAsMjMuMTU0LDguMTg5LDIzLjE1NCwxOC4yODdhMTYuMzY0LDE2LjM2NCwwLDAsMS02LjEzMiwxMi40Yy4xNDYsMy4xNzUuOCw3LjQ0NCwzLjExNiw5LjY0Ni00LjQyMiwwLTguOTUxLTIuOTI2LTExLjYzNi01LjAzNGEyOC40NjMsMjguNDYzLDAsMCwxLTguNSwxLjI3N0MxMC4zNjYsMzcuNTA5LDAsMjkuMzIsMCwxOS4yMjJTMTAuMzY2LjkzNSwyMy4xNTQuOTM1WiIgdHJhbnNmb3JtPSJtYXRyaXgoMC45OSwgLTAuMSwgMC4xLCAwLjk5LCA3LjksIDkuOTEpIiBvcGFjaXR5PSIwLjA5NyIvPgogICAgICA8L2c+CiAgICA8L2c+CiAgICA8ZyB0cmFuc2Zvcm09Im1hdHJpeCgxLCAwLCAwLCAxLCAyNC4zNiwgMTg4LjY5KSIgZmlsdGVyPSJ1cmwoI3BhdGg1KSI+CiAgICAgIDxwYXRoIGlkPSJwYXRoNS0yIiBkYXRhLW5hbWU9InBhdGg1IiBkPSJNMTYuODksMjQuNTA4aDBhMi4zNCwyLjM0LDAsMCwwLDIuNTI4LDIuMjEyQTMuMzMyLDMuMzMyLDAsMCwwLDIyLjEsMjUuM2MwLS4xNTgtLjE1OC0uNDc0LS4zMTYtLjQ3NHMtLjMxNi40NzQtMS4xMDYuNDc0Yy0xLjI2NCwwLTEuMjY0LTEuMjY0LTEuMjY0LTIuNjg2VjEyLjY1N2MtLjc5LDAtMS43MzguMzE2LTIuNTI4LjMxNlYyMy4wODZBNi4yMTksNi4yMTksMCwwLDEsMTIuNzgxLDI1LjNjLTEuOSwwLTIuMzctMS41OC0yLjM3LTMuNDc2VjE1LjY1OWMwLTEuMTA2LS4xNTgtMy0uMTU4LTMtLjk0OCwwLTEuOS4zMTYtMi42ODYuMzE2LDAsMCwuMzE2LDIuMzcuMzE2LDMuMzE4djUuODQ2YzAsMS45LjMxNiwzLjQ3Ni4zMTYsNC41ODIsMCwxLjktLjQ3NCwzLjMxOC0uNDc0LDUuMDU2QTIuMjE0LDIuMjE0LDAsMCwwLDkuNDYzLDMzLjgzYy43OSwwLDEuNDIyLS42MzIsMS40MjItMS45LDAtMS40MjItMS4xMDYtMy42MzQtMS4xMDYtNS42ODgsMC0uMTU4LjE1OC0uMzE2LjQ3NC0uMzE2YTIuMzY3LDIuMzY3LDAsMCwwLDEuOS43OUE1LjkyNCw1LjkyNCwwLDAsMCwxNi44OSwyNC41MDhaTTE2Ljg5LDI0LjUwOFoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDE5LjA3IDQuNzQpIi8+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4=


logoUrl: https://raw.githubusercontent.com/cncf/artwork/refs/heads/main/projects/kubernetes/stacked/color/kubernetes-stacked-color.png

source:
  type: marketplace
  reference: 16132843

# source:
#   type: quickstart


locale: "en"
variableGroups:
  - title: "Basic Hidden"
    variables:
    - tenancy_ocid
    - region
    - user_ocid
    visible: false

  - title: "OKE Network Configuration"
    variables:
    - create_vcn
    - oke_vcn_compartment_id
    - vcn_cidrs
    - vcn_id

  - title: "OKE Cluster Configuration"
    variables:
    - oke_cluster_name
    - oke_cluster_compartment_id
    - oke_kubernetes_version
    - oke_show_advanced_options
    - oke_network_type
    - oke_cluster_endpoint_visibility

  - title: "OKE Node Pool Configuration"
    variables:
    - oke_create_multiple_node_pool
    - oke_node_pool_name   
    - oke_node_pool_size
    - oke_node_pool_instance_shape
    - oke_node_boot_volume_size
    - oke_enable_node_pool   
    - oke_node_pool_properties
    - oke_ssh_private_key
    - oke_ssh_public_key

variables:
  oke_cluster_compartment_id:
    type: oci:identity:compartment:id
    title: "OKE Cluster Compartment"
    description: "The compartment where you want to create OKE cluster"
    default: compartment_ocid
    required: true

  oke_cluster_name:
    type: string
    title: "OKE Cluster Name"
    description: "Provide OKE cluster name"
    default: "okecluster"
    required: false
    pattern: "^[A-Za-z0-9_-]{3,20}$"

  oke_kubernetes_version:
    type: oci:kubernetes:versions:id
    title: "Kubernetes Version"
    description: "Provide Kubernetes Version"
    dependsOn:
      compartmentId: oke_cluster_compartment_id
      clusterOptionId: "all"
    required: true
    visible: true

  oke_show_advanced_options:
    type: boolean
    default: false
    title: "Advanced options"
    description: "Shows advanced options for OKE"
    visible: true

  oke_network_type:
    type: enum
    enum:
    - "Flannel"
    - "VCN-native pod networking"
    title: "OKE Network Type"
    description: "Provide Network Type"
    required: true
    visible:
      and:
        - oke_show_advanced_options

  oke_cluster_endpoint_visibility:
    type: enum
    enum:
    - "Private"
    - "Public"
    default: "Private"
    title: "Choose Kubernetes API Endpoint visibility type"
    description: "Kubernetes API Endpoint visibility type"
    required: true
    visible:
      and:
        - oke_show_advanced_options

  create_vcn:
    type: boolean
    title: "Create new VCN"
    description: "Whether to create a Virtual Cloud Network for OKE Cluster"
    required: false
    visible: true

  oke_vcn_compartment_id:
    type: oci:identity:compartment:id
    title: "OKE VCN Compartment"
    description: "The compartment where you want to create OKE VCN"
    default: compartment_ocid
    required: true

  vcn_cidrs:
    type: array
    items:
      type: string
    title: "List of VCN cidrs"
    description: "The list of IPv4 CIDR blocks the VCN will use"
    default: ["10.0.0.0/16"]
    required: true
    visible:
      and:
        - create_vcn

  vcn_id:
    type: oci:core:vcn:id
    title: Existing VCN
    description: An existing Virtual Cloud Network (VCN) where OKE Cluster will be provisioned"
    dependsOn:
      compartmentId: oke_vcn_compartment_id 
    required: true
    visible:
      not:
        - create_vcn

  oke_create_multiple_node_pool:
    type: boolean
    default: false
    title: "Create Multiple Node Pools"
    description: "Whether to create more than one node pool for OKE cluster"
    visible: true

  # oke_node_pool_name:
  #   type: string
  #   title: "Node Pool Name"
  #   description: "OKE Cluster Node Pool Name"
  #   default: "nodepool-1"
  #   required: false
  #   pattern: "^[A-Za-z0-9-]+$"
  #   visible:
  #     and:
  #       - eq:
  #         - oke_node_pool_size
  #         - 1

  oke_node_pool_name:
    type: string
    title: "Node Pool Name"
    description: "OKE Cluster Node Pool Name"
    default: "nodepool-1"
    required: false
    pattern: "^[A-Za-z0-9-]+$"
    visible:
      not:
        - oke_create_multiple_node_pool

  oke_node_pool_size:
    type: number
    title: "OKE Cluster Node Pool Size"
    description: "The number of nodes in the OKE cluster node pool"
    default: 1
    required: true
    pattern: "^[0-9]+$"
    visible:
      not:
        - oke_create_multiple_node_pool 

  oke_node_pool_instance_shape:
    type: oci:core:instanceshapewithflex:name
    title: "Select a shape for the Worker Nodes instances"
    required: true
    dependsOn:
      compartmentId: oke_cluster_compartment_id
    visible:
      not:
        - oke_create_multiple_node_pool 

  oke_node_boot_volume_size:
    type: number
    title: "Node pool boot volume size"
    default: 50
    required: true
    minimum: 50
    visible:
      not:
        - oke_create_multiple_node_pool 

  oke_enable_node_pool:
    type: boolean
    default: true
    title: "Create Node Pool"
    description: "Whether to enable node pool for OKE cluster"
    visible:
      not:
        - oke_create_multiple_node_pool

  oke_node_pool_properties:
    type: object
    title: "OKE Node Pool Properties"
    description: "Multiple Node pool properties"
    default: |
      {
        "node-pools": {
          "nodepool-1": {
            "create": true,
            "mode": "node-pool",
            "size": 1,
            "shape": "VM.Standard.E4.Flex",
            "ocpus": 1,
            "memory": 16,
            "boot_volume_size": 50
          },
          "nodepool-2": {
            "create": true,
            "mode": "node-pool",
            "size": 1,
            "shape": "VM.Standard.E4.Flex",
            "ocpus": 1,
            "memory": 16,
            "boot_volume_size": 50
          }
        }
      }
    visible:
      and:
        - oke_create_multiple_node_pool

  oke_ssh_public_key:
    title: SSH public key
    description: Public SSH key for compute access.
    # renders variable as an SSH key control
    type: oci:core:ssh:publickey
    additionalProps:
      allowMultiple: true
    required: true
    default: []
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"

  oke_ssh_private_key:
    type: file
    title: SSH private key
    description: UPload ssh private key
    required: true

  # oke_cluster_properties:
  #   type: object
  #   title: "OKE Cluster Properties"
  #   description: "OKE Cluster Properties"
  #   default: |
  #     {
  #       "cluster_name": "blue",
  #       "cni": "flannel",
  #       "cluster_type": "enhanced",
  #       "vcn_cidr": ["10.0.0.0/16"],
  #       "bastion_allowed_cidrs": ["0.0.0.0/0"],
  #       "control_plane_is_public": false,
  #       "worker_pools": {
  #         "housekeeping": {
  #           "create": true,
  #           "mode": "node-pool",
  #           "size": 1,
  #           "shape": "VM.Standard.E4.Flex",
  #           "ocpus": 1,
  #           "memory": 16,
  #           "boot_volume_size": 50
  #         }
  #       }
  #     }
